### ISSUE TITLE
Quiet Day Jank

### ISSUE THREAD

**Issue by JackFrost2424** [vlggms/lobotomy-corp13#1068]
Issue with Quiet Day: 
Due to some jank that I don't know the exact details of, the abnormality will eventually lock up and will stop responding, resulting in no buffs being given out. This has been a consistent issue in the rounds I have played with it in. 

After attempting to get a second buff of a stat, it would fail to go through. (So, I would get +15 temperance the first time, it expires, then it doesn't trigger). It would be fine if I did another work to get that work's buff. Eventually, it would stop respond all together and be a wasted work. 

Possible reasons it could be like this: Jank from the work not finishing until the story is over? Because when the story for the buff is told, the work is still going on until it is finished. Might be an issue with the status effects themselves? 
How to replicate: Attempt to get multiple work buffs of the same type from the abno (so two attachment buffs, two insights, etc etc). Then compare that to a freshly gotten buff (attachment, then insight). Ideally, you should notice the abno freezing up and not telling its stories.

**Comment by Coxswain-Navigator** [comment]
Was not able to replicate this in testing, it would be a great help if the exact cause could be determined.
