### ISSUE TITLE
Pygmallion can Resane people on hostile breach

### ISSUE THREAD

**Issue by TaculoTaculo** [vlggms/lobotomy-corp13#1184]
## Reproduction:
join in
have Pygmallion breach in her hostile form
her projectiles will hit you, making you insane
she will keep attacking you, taking you back to sanity again
repeat the cycle of infinite resaning and insanity

![Pygging](https://github.com/vlggms/lobotomy-corp13/assets/115740526/ea350d9e-59c1-4731-bdf0-fa96a60db07f)

**Comment by Kitsunemitsu** [comment]
Was really hoping I wasn't going to have to deal with this. 
Will notify the dev.

**Comment by EnderMage99** [comment]
Fixed in  #1190
