### ISSUE TITLE
Throwables not registering LC armors

### ISSUE THREAD

**Issue by scionalu** [vlggms/lobotomy-corp13#1254]
## Bug
Thrown items hitting living mobs doesn't consider their armors because old TG only considered thrown items doing Melee damage
We forgot to convert it to thrown_item.damtype for LC13 purposes. The file is "living_defenses.dm"
Would also need a check if the damtype exist or not, and put it back to MELEE if it doesn't
![image](https://github.com/vlggms/lobotomy-corp13/assets/80381079/b4815545-f37a-41db-b648-b094346eca71)

**Comment by Kitsunemitsu** [comment]
Fixed a while ago.
