### ISSUE TITLE
Items display as "In stock" when out of stock

### ISSUE THREAD

**Issue by chesse20** [vlggms/lobotomy-corp13#1286]
## Round ID:

Round ID: [5070](https://scrubby.melonmesa.com/round/5070)

## Testmerges:
[#1234: 'adds buttons to a few playable abnormalities' by TaculoTaculo at commit 19981279d7](https://www.github.com/vlggms/lobotomy-corp13/pull/1234)
[#1217: 'Work damage is now consistent' by Kitsunemitsu at commit 2d6b6a835d](https://www.github.com/vlggms/lobotomy-corp13/pull/1217)
[#1267: 'Core Suppressions rework' by EgorDinamit at commit 4365e6ebf6](https://www.github.com/vlggms/lobotomy-corp13/pull/1267)
[#1252: 'The City Map' by Kitsunemitsu at commit 584d096d32](https://www.github.com/vlggms/lobotomy-corp13/pull/1252)
[#1271: 'Rep Console Update' by Kitsunemitsu at commit 40bb908379](https://www.github.com/vlggms/lobotomy-corp13/pull/1271)
[#1257: 'adds looc' by Kitsunemitsu at commit 0255bf30d5](https://www.github.com/vlggms/lobotomy-corp13/pull/1257)
[#1001: 'Ordeals of gold - Dawn through Dusk' by Coxswain-Navigator at commit 628ac7950c](https://www.github.com/vlggms/lobotomy-corp13/pull/1001)
[#1263: 'Talking Bubbles' by LanceSmites328 at commit ab8b84fc97](https://www.github.com/vlggms/lobotomy-corp13/pull/1263)

## Reproduction:
Buy items from machines with limited supply.
Red text that says in stock despite no stock
![image](https://github.com/vlggms/lobotomy-corp13/assets/9161779/89d360da-16df-400d-94b7-e634800a5b47)
![image](https://github.com/vlggms/lobotomy-corp13/assets/9161779/dc2317b5-d997-4eba-8084-df0bb586e8d7)

**Comment by InsightfulParasite** [comment]
Weirdly enough the only indicator for it being out of stock is the color... which is weird for reasons. 
![image](https://github.com/vlggms/lobotomy-corp13/assets/109536843/c43dfaa9-20ee-4091-bd12-b96dd793cdb8)

**Comment by InsightfulParasite** [comment]
I found the thing in TGUI. It seems the original creator of the UI only had the color code of green yellow red for it to indicate amount left.

**Comment by InsightfulParasite** [comment]
https://github.com/vlggms/lobotomy-corp13/pull/1596
