### ISSUE TITLE
Liver Parasite not removed by removal of liver 

### ISSUE THREAD

**Issue by chesse20** [vlggms/lobotomy-corp13#1287]
## Round ID:

Round ID: [5070](https://scrubby.melonmesa.com/round/5070)

## Testmerges:
[#1234: 'adds buttons to a few playable abnormalities' by TaculoTaculo at commit 19981279d7](https://www.github.com/vlggms/lobotomy-corp13/pull/1234)
[#1217: 'Work damage is now consistent' by Kitsunemitsu at commit 2d6b6a835d](https://www.github.com/vlggms/lobotomy-corp13/pull/1217)
[#1267: 'Core Suppressions rework' by EgorDinamit at commit 4365e6ebf6](https://www.github.com/vlggms/lobotomy-corp13/pull/1267)
[#1252: 'The City Map' by Kitsunemitsu at commit 584d096d32](https://www.github.com/vlggms/lobotomy-corp13/pull/1252)
[#1271: 'Rep Console Update' by Kitsunemitsu at commit 40bb908379](https://www.github.com/vlggms/lobotomy-corp13/pull/1271)
[#1257: 'adds looc' by Kitsunemitsu at commit 0255bf30d5](https://www.github.com/vlggms/lobotomy-corp13/pull/1257)
[#1001: 'Ordeals of gold - Dawn through Dusk' by Coxswain-Navigator at commit 628ac7950c](https://www.github.com/vlggms/lobotomy-corp13/pull/1001)
[#1263: 'Talking Bubbles' by LanceSmites328 at commit ab8b84fc97](https://www.github.com/vlggms/lobotomy-corp13/pull/1263)

## Reproduction:

Player infected with "Liver parasite"
![image](https://github.com/vlggms/lobotomy-corp13/assets/9161779/249964cc-a2cd-46ec-8919-edf0d0375137)

After replacement of liver with cybernetic liver, Parasite still present
![image](https://github.com/vlggms/lobotomy-corp13/assets/9161779/bb4ef8ab-bb50-41cd-a8db-c23826934349)

**Comment by InsightfulParasite** [comment]
Oh this is weird. Did you hold the liver in your hands or did you do that quick switch thing. Hold on i may make a check for it to be cured on inorganic livers.

**Comment by InsightfulParasite** [comment]
https://github.com/vlggms/lobotomy-corp13/pull/1314 This may fix it.

**Comment by InsightfulParasite** [comment]
Okay turns out it was broken from the start but i may have managed to fix it.

**Comment by chesse20** [comment]
you can replace a liver without removing it entirely? also thanks
