### ISSUE TITLE
Painting and Photo frames can't be placed on walls

### ISSUE THREAD

**Issue by chesse20** [vlggms/lobotomy-corp13#1288]
## Round ID:
[5072](https://scrubby.melonmesa.com/round/5072)

## Testmerges:
[#1234: 'adds buttons to a few playable abnormalities' by TaculoTaculo at commit 19981279d7](https://www.github.com/vlggms/lobotomy-corp13/pull/1234)
[#1217: 'Work damage is now consistent' by Kitsunemitsu at commit 2d6b6a835d](https://www.github.com/vlggms/lobotomy-corp13/pull/1217)
[#1267: 'Core Suppressions rework' by EgorDinamit at commit 4365e6ebf6](https://www.github.com/vlggms/lobotomy-corp13/pull/1267)
[#1252: 'The City Map' by Kitsunemitsu at commit 584d096d32](https://www.github.com/vlggms/lobotomy-corp13/pull/1252)
[#1271: 'Rep Console Update' by Kitsunemitsu at commit 40bb908379](https://www.github.com/vlggms/lobotomy-corp13/pull/1271)
[#1257: 'adds looc' by Kitsunemitsu at commit 0255bf30d5](https://www.github.com/vlggms/lobotomy-corp13/pull/1257)
[#1001: 'Ordeals of gold - Dawn through Dusk' by Coxswain-Navigator at commit 628ac7950c](https://www.github.com/vlggms/lobotomy-corp13/pull/1001)
[#1263: 'Talking Bubbles' by LanceSmites328 at commit ab8b84fc97](https://www.github.com/vlggms/lobotomy-corp13/pull/1263)

## Reproduction:

If you make a photo or picture frame nothing happens when you try and install it on the reinforced walls that are used in most maps. This means you can't decorate your offices or employee housing areas with paintings or photos.

**Comment by chesse20** [comment]
Spraypainting can't be used either idk if that needs a seperate issue

**Comment by InsightfulParasite** [comment]
Indestructable apparently doesnt count as a walltype.

**Comment by InsightfulParasite** [comment]
Oh so the code is actually in turf/closed/wall attacked_by.

**Comment by InsightfulParasite** [comment]
https://github.com/vlggms/lobotomy-corp13/pull/1597
