### ISSUE TITLE
Cleanbots have a broken patrol path on Facility C

### ISSUE THREAD

**Issue by chesse20** [vlggms/lobotomy-corp13#1292]
## Round ID:
[5103](https://scrubby.melonmesa.com/round/5103)

## Testmerges:
[#1217: 'Work damage is now consistent' by Kitsunemitsu at commit 2d6b6a835d](https://www.github.com/vlggms/lobotomy-corp13/pull/1217)
[#1273: 'Adds hammer of light' by Coxswain-Navigator at commit f6c498248d](https://www.github.com/vlggms/lobotomy-corp13/pull/1273)
[#1269: 'Adds backwards clock' by Coxswain-Navigator at commit b8987dc167](https://www.github.com/vlggms/lobotomy-corp13/pull/1269)
[#1267: 'Core Suppressions rework' by EgorDinamit at commit 4365e6ebf6](https://www.github.com/vlggms/lobotomy-corp13/pull/1267)
[#1271: 'Rep Console Update' by Kitsunemitsu at commit a507528aa0](https://www.github.com/vlggms/lobotomy-corp13/pull/1271)
[#1248: 'Adds Wayward Passenger' by vampirebat74 at commit c449d1700d](https://www.github.com/vlggms/lobotomy-corp13/pull/1248)
[#1247: 'Adds spirit of Falada' by Coxswain-Navigator at commit e974655712](https://www.github.com/vlggms/lobotomy-corp13/pull/1247)
[#1234: 'adds buttons to a few playable abnormalities' by TaculoTaculo at commit d9ef278b42](https://www.github.com/vlggms/lobotomy-corp13/pull/1234)

## Reproduction:
Go on Facility C
walk into the dumpster room inside welfare department

https://github.com/vlggms/lobotomy-corp13/assets/9161779/43db9925-3179-4a39-bfcf-ccbe79e4c9da

**Comment by Coxswain-Navigator** [comment]
![image](https://github.com/vlggms/lobotomy-corp13/assets/35991533/64a7bb18-d0ca-47c0-8989-e05cb391fd60)

**Comment by InsightfulParasite** [comment]
I wonder if its trying to clean something under the conveyor belt.

**Comment by InsightfulParasite** [comment]
Unsure if this was ever solved but we turned off patrolling for cleanbots to reduce strain on the server.
