### ISSUE TITLE
Fix Vendor Code or make Ego Armor not have the same name as their Weapon.

### ISSUE THREAD

**Issue by InsightfulParasite** [vlggms/lobotomy-corp13#1375]
![image](https://github.com/vlggms/lobotomy-corp13/assets/109536843/d2615659-abf4-47ce-9efd-81a641386b96)
Vendors will display items as the same thing if they share the same name. This makes storing Ego more difficult.

**Comment by InsightfulParasite** [comment]
I feel sort of frustrated at this because even if we use the end of the obj type name we would still end up with the same issue. Like i would take time out of my day to rename each of the armors to suit or add a automated initialize suit suffix thing but i dont know if we are avoiding that solution because in the original game it was indistinguishable names or because it would cause conflicts.

**Comment by Coxswain-Navigator** [comment]
You would have to do something similar to how this problem is solved in the ego datum for weapons that share a name.

**Comment by InsightfulParasite** [comment]
> You would have to do something similar to how this problem is solved in the ego datum for weapons that share a name.

I dont think that would work since vendors apply to almost everything and adding in a small "if armor then add armor to the end" feels almost spaghetti code. 
`
	for(var/datum/abnormality/A in SSlobotomy_corp.all_abnormality_datums)
		if(!LAZYLEN(A.ego_datums))
			continue
		if(A.threat_level != selected_level)
			continue
		dat += "[A.name] ([A.stored_boxes] PE):<br>"
		for(var/datum/ego_datum/E in A.ego_datums)
			dat += " <A href='byond://?src=[REF(src)];purchase=[E.name][E.item_category]'>[E.item_category] - [E.name] ([E.cost] PE)</A>"
			var/info = html_encode(E.PrintOutInfo())
			if(info)
				dat += " - <A href='byond://?src=[REF(src)];info=[info]'>Info</A>"
			dat += "<br>"
		dat += "<br>"
		`
I dont know if you mean this but the extraction console for ego doesnt derive it from the item themselves it derives it from a ego_datum that has a item_catagory variable that is listed with the name.

**Comment by InsightfulParasite** [comment]
Hold on i just noticed something in the code i posted where md5 uses o.name

**Comment by InsightfulParasite** [comment]
Cursed issue. Worked around it by making unique smart fridges for ego but i still look back on this.

**Comment by Kitsunemitsu** [comment]
Was fixed with two fridges
