### ISSUE TITLE
Gold Ordeal Going Invisible On Death

### ISSUE THREAD

**Issue by scionalu** [vlggms/lobotomy-corp13#1476]
Peccatulum Superbiae goes invisible on death without despawning, 
making it a free meal for Matriarch and the likes because most people can't see it

(code/modules/mob/living/simple_animal/hostile/ordeal/gold.dm) 
(/mob/living/simple_animal/hostile/ordeal/sin_pride)

**Comment by Coxswain-Navigator** [comment]
Fixed in https://github.com/Coxswain-Navigator/lobotomy-corp13/commit/f66f5b13ca3d177f0892f721fb68570dca1b4de4
