### ISSUE TITLE
Consoles in E Facility houses are unpowered

### ISSUE THREAD

**Issue by chesse20** [vlggms/lobotomy-corp13#560]
## Round ID:
[1934](https://scrubby.melonmesa.com/round/1934)

## Testmerges:
#533 

## Reproduction:
Click Console in bedroom.
"You press the power button but the console does not respond."

**Comment by civilCornball** [comment]
I'll see what I can do.
(Certainly've left this long enough, heh)

**Comment by Kitsunemitsu** [comment]
E-Corp has been discontinued.

**Comment by Kitsunemitsu** [comment]
Misclick, There is no real intention to fix Ecorp at this time, especially such a minor issue
