### ISSUE TITLE
White nights & Ebony queen's weapons have infinite range

### ISSUE THREAD

**Issue by Gboster-0** [vlggms/lobotomy-corp13#602]
Basically the title, white nights and ebony queens weapons ranged ability can be triggered from any range, and with the use of camera consoles you can fire it from managers office onto any threat. this was known for quite a long while but no one bothered to fix it. Leaving this bug report for Cogswain to remind later.

## Reproduction:

1. Obtain one of the two weapons
2. Go to managers office
3. Get the weapon in your main hand, and use the managerial console
4. Use the weapon's ranged abilities on abnormalities through the managerial console

**Comment by Coxswain-Navigator** [comment]
I'll look into this when ebony queen's apple gets merged.
