### ISSUE TITLE
Queen of Hatred can teleport on top of interns in the Tutorial

### ISSUE THREAD

**Issue by Auris456852** [vlggms/lobotomy-corp13#799]
## Testmerges:

Likely unrelated, but...

[#764: 'Adds 3 new tool abnormalities' by Coxswain-Navigator at commit 2ddc91ffa8](https://www.github.com/vlggms/lobotomy-corp13/pull/764)
[#508: 'Saltmine Corp' by randal-the-vandal at commit 54405608a1](https://www.github.com/vlggms/lobotomy-corp13/pull/508)
[#706: 'LC13 gamemodes' by monochromatism at commit 4b07ab2cc4](https://www.github.com/vlggms/lobotomy-corp13/pull/706)
[#551: 'Lobotomy Corp UI Theme' by Kitsunemitsu at commit d73939a2cf](https://www.github.com/vlggms/lobotomy-corp13/pull/551)
[#784: 'Adds PE Refining' by Kitsunemitsu at commit 4bef554b2e](https://www.github.com/vlggms/lobotomy-corp13/pull/784)
[#793: 'Crumbling armor changes' by Coxswain-Navigator at commit fcd77d7d9f](https://www.github.com/vlggms/lobotomy-corp13/pull/793)
[#783: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit 96858e5faa](https://www.github.com/vlggms/lobotomy-corp13/pull/783)
[#779: 'Most abnormalities now share faction' by EgorDinamit at commit d8b9003d3c](https://www.github.com/vlggms/lobotomy-corp13/pull/779)
[#798: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit f6fbbac08e](https://www.github.com/vlggms/lobotomy-corp13/pull/798)
[#786: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit c6cc7efbeb](https://www.github.com/vlggms/lobotomy-corp13/pull/786)

## Reproduction: 

Someone was simply playing the tutorial, when suddenly, after shuttle arrived with QoH presumably on it, it teleported on top of them. Maybe limit its teleportation if it's on that Z-level...?

**Comment by Coxswain-Navigator** [comment]
Need a confirmation that this an actual issue that still happens. Local testing, and the code (which precede this issue) both prove this false. Maybe the issue is actually what z-level the tutorial is on in some maps?

**Comment by out-of-phaze** [comment]
> Need a confirmation that this an actual issue that still happens. Local testing, and the code (which precedes this issue) both prove this false. Maybe the issue is actually what z-level the tutorial is on in some maps?

Are you sure you tested it with the QoH taking the shuttle?

**Comment by out-of-phaze** [comment]
There's probably a better solution, like limiting teleportation to levels with the station trait.

**Comment by InsightfulParasite** [comment]
QoH while in the Managers office will teleport to interns.

**Comment by Coxswain-Navigator** [comment]
I'm fairly certain that the tutorial is now on a different Z level, and so this will no longer happen.

**Comment by out-of-phaze** [comment]
> There's probably a better solution, like limiting teleportation to levels with the station trait.

**Comment by InsightfulParasite** [comment]
> > There's probably a better solution, like limiting teleportation to levels with the station trait.

We do have components like stationstuck.dm that can teleport or gib things that leave the station z level.

**Comment by InsightfulParasite** [comment]
The only issue is that keeping her on a single Z level may result in... not issues but complaints.
