### ISSUE TITLE
Nothing there shells can move horizontally

### ISSUE THREAD

**Issue by Coxswain-Navigator** [vlggms/lobotomy-corp13#859]
![image](https://user-images.githubusercontent.com/35991533/232675440-515c46d3-8836-4ae3-945f-ead677fc144e.png)

Probably a long-standing issue with using human sprites for simple mobs and the like. Someone ought to look at how it's done and make improvements to prevent this sort of thing from happening.

**Comment by vampirebat74** [comment]
It has to do with the appearance variable. I'm personally not too familiar with it overall but it copies one sprite and sets it for every icon state, or prioritizes it above them.

**Comment by out-of-phaze** [comment]
Appearance copies *all* the appearance vars, including overlays, icon state, and most importantly, transform. Transform is why they appear horizontal. You should reset it for the shells.
