### ISSUE TITLE
please fix violet midnight

### ISSUE THREAD

**Issue by missLlucky** [vlggms/lobotomy-corp13#908]
- its been out for 3 months now egor, its absolutely too strong and half the time its strenght isn't coming from itself
 
- it can double hit at times for no reason making pale a flat out insta kill for anyone who's not wearing pale 5+
- and pale can straight up attack before showing up...

HALF THE TIME PEOPLE DON'T HAVE ALEPH EGO WHIT HOW HIGH POP WERE GETTING AT TIMES

**Comment by Kitsunemitsu** [comment]
Balance issue, not for the Github.
